### ISSUE TITLE
Origin 'null' issue on Stix-Web font in Chrome

### ISSUE THREAD

**Issue by drlippman** [mathjax/MathJax#926]
In Chrome 37.0.2062.120, when MathJax (2.4-beta-2 off CDN) is configured to use the Stix Web fonts, I am getting the error:

```
Font from origin 'null' has been blocked from loading by Cross-Origin Resource Sharing policy: Received an invalid response. Origin 'http://dlippman.imathas.com' is therefore not allowed access.
```

For a test case, visit http://dlippman.imathas.com/mjtest.html

In case it might be helpful, here's what I'm seeing in the network pane, that I'm guessing is related:
![chromemjissue](https://cloud.githubusercontent.com/assets/190505/4381810/ea7c5332-437b-11e4-98a4-f6465c177ae1.jpg)

**Comment by yrral86** [comment]
I'm also seeing this using the Latin-modern font.  The strange thing is, I only see it one one of two identical servers.  On the server I do see the error, it is rendering with HTML-CSS even though I have it configured to use SVG.  Would this error cause the SVG renderer to fail so it falls back to HTML-CSS?  We have some code that doesn't display correctly with HTML-CSS, so it is important that we use SVG.  Is there anything I can do to fix this or otherwise restore SVG rendering.

**Comment by dpvc** [comment]
@yrral86, have you used the MathJax contextual menu to switch renderers on one of the servers?  That setting is sticky, and overrides the page setting, so you might look to see if there is a MathJax cookie for the one server and delete that.  See if that helps.

Can you give some examples of code that doesn't display correctly with HTML-CSS but does with SVG?  We would like to fix the problems.

**Comment by dpvc** [comment]
@drlippman, the error message is normal and is due to a test that MathJax does to see what the response is to a nonexistent web font.  MathJax uses `about:blank` as the font in order to avoid any network traffic for the test.  The warning message is expected, and in order to prevent that, MathJax would have to do additional network accesses, which is not worth it.

**Comment by yrral86** [comment]
Sorry for the noise... I forget to check for the cookie.  

Our biggest issue is this: https://github.com/mathjax/MathJax/issues/1095, but fractions also look nicer with the SVG renderer.  HTML-CSS also seems to frequently add extra spacing to the right of the expression.

**Comment by dpvc** [comment]
No problem.  Glad that was all it was.

Thanks for the information about the problems you are encountering.  Certainly 1095 is a pain; I have an idea for it, and will see if I can improve it.  In terms of the extra spacing, I think that should have been fixed in version 2.5.3.  (There was an issue with the measurements in the original 2.5 release.)

**Comment by andrenarchy** [comment]
@dpvc Can you point me to the code where this request is initiated? And can you explain why there needs to be a test for the response to a non-existing (or to be precise: blocked) font?

Unfortunately, we still see this *error* message (it's not a *warning*) in Chrome 44.0.2403.155.

**Comment by mikkorantalainen** [comment]
Would it be possible to avoid the error in console if the test were done wrapped in try {} catch {} logic? If avoiding the error is not possible, how about adding a console.log message before the test? Something like "MathJax: testing how this browser handles non-existing web font...". If web developer sees the error about failing font load after that, it would not be considered a real issue.
